// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';
import {context} from '../models';

export function Connect(arg1:string):Promise<string>;

export function DeleteConnection(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function GetConnection(arg1:string):Promise<models.ConnectionProfile>;

export function GetMasterPasswordStatus():Promise<services.MasterPasswordStatus>;

export function InitializeMasterPassword(arg1:string):Promise<void>;

export function ListConnections():Promise<Array<models.ConnectionProfile>>;

export function LockMasterPassword():Promise<void>;

export function SaveConnection(arg1:models.ConnectionProfile):Promise<models.ConnectionProfile>;

export function SetMasterPassword(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function TestConnection(arg1:models.ConnectionProfile):Promise<Record<string, any>>;
