// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['services']['ConnectionService']['Connect'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['services']['ConnectionService']['DeleteConnection'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['services']['ConnectionService']['Disconnect'](arg1);
}

export function GetConnection(arg1) {
  return window['go']['services']['ConnectionService']['GetConnection'](arg1);
}

export function GetMasterPasswordStatus() {
  return window['go']['services']['ConnectionService']['GetMasterPasswordStatus']();
}

export function InitializeMasterPassword(arg1) {
  return window['go']['services']['ConnectionService']['InitializeMasterPassword'](arg1);
}

export function ListConnections() {
  return window['go']['services']['ConnectionService']['ListConnections']();
}

export function LockMasterPassword() {
  return window['go']['services']['ConnectionService']['LockMasterPassword']();
}

export function SaveConnection(arg1) {
  return window['go']['services']['ConnectionService']['SaveConnection'](arg1);
}

export function SetMasterPassword(arg1) {
  return window['go']['services']['ConnectionService']['SetMasterPassword'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['ConnectionService']['Startup'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['services']['ConnectionService']['TestConnection'](arg1);
}
